### ISSUE TITLE
Facebook Login is not working

### ISSUE THREAD

**Issue by Samsemilio** [CO-OPEN/Mangos#2]
![bildschirmfoto 2015-10-12 um 18 38 58](https://cloud.githubusercontent.com/assets/747161/10433249/8fe05734-7110-11e5-8ba4-1646ef50b75f.png)

**Comment by Samsemilio** [comment]
It works on mangos.meteor.com, but not on mangos.liv.io

**Comment by Samsemilio** [comment]
Fixed: eb3f9fc0b82f0d9573468dcb912d601ac3dd9b8b

**Comment by Arcurus** [comment]
facebook not working? thats not a bug, thats a future :)
